preset: psr1

enabled:
  - alpha_ordered_imports
  - binary_operator_spaces
  - blank_line_after_namespace
  - blank_line_after_opening_tag
  - cast_spaces
  - class_definition
  - concat_without_spaces
  - dir_constant
  - ereg_to_preg
  - function_typehint_space
  - hash_to_slash_comment
  - include
  - is_null
  - linebreak_after_opening_tag
  - lowercase_cast
  - lowercase_constants
  - lowercase_keywords
  - magic_constant_casing
  - method_argument_space
  - method_separation
  - method_visibility_required
  - modernize_types_casting
  - native_function_casing
  - new_with_braces
  - no_blank_lines_after_class_opening
  - no_blank_lines_after_phpdoc
  - no_blank_lines_after_return
  - no_blank_lines_between_imports
  - no_blank_lines_between_traits
  - no_closing_tag
  - no_extra_block_blank_lines
  - no_empty_comment
  - no_empty_phpdoc
  - no_empty_statement
  - no_extra_consecutive_blank_lines
  - no_leading_import_slash
  - no_leading_namespace_whitespace
  - no_multiline_whitespace_around_double_arrow
  - no_multiline_whitespace_before_semicolons
  - no_php4_constructor
  - no_singleline_whitespace_before_semicolons
  - no_spaces_after_function_name
  - no_spaces_inside_offset
  - no_spaces_inside_parenthesis
  - no_spaces_outside_offset
  - no_trailing_comma_in_singleline_array
  - no_trailing_whitespace
  - no_unreachable_default_argument_value
  - no_useless_else
  - no_useless_return
  - no_whitespace_before_comma_in_array
  - non_printable_character
  - normalize_index_brace
  - object_operator_without_whitespace
  - phpdoc_annotation_without_dot
  - phpdoc_indent
  - phpdoc_no_access
  - phpdoc_no_useless_inheritdoc
  - phpdoc_single_line_var_spacing
  - phpdoc_trim
  - phpdoc_type_to_var
  - phpdoc_types
  - property_visibility_required
  - self_accessor
  - semicolon_after_instruction
  - short_array_syntax
  - short_scalar_cast
  - single_blank_line_at_eof
  - single_blank_line_before_namespace
  - single_class_element_per_statement
  - single_import_per_statement
  - single_line_after_imports
  - single_quote
  - standardize_not_equals
  - strict_comparison
  - switch_case_semicolon_to_colon
  - switch_case_space
  - ternary_operator_spaces
  - trailing_comma_in_multiline_array
  - trim_array_spaces
  - unalign_double_arrow
  - unalign_equals
  - unary_operator_spaces
  - unix_line_endings

finder:
  name:
    - "*.php"
