#
# https://circleci.com/docs/2.0/language-php/
#

version: 2
jobs:
  build:
    docker:
    - image: circleci/php:7.1.20-cli-stretch

    working_directory: ~/prismoquent

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run: mkdir -p ~/phpunit

      - run: ./vendor/bin/phpunit -c ~/prismoquent/phpunit.xml --log-junit ~/phpunit/junit.xml

      - store_test_results:
          path: ~/phpunit

      - store_artifacts:
          path: ~/phpunit

